# Generated by Django 5.2.15 on 2026-06-23 06:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('center', '0001_initial'),
        ('subcenter', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('identifier', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_forms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'forms_definition',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[('TEXT', 'Text'), ('TEXTAREA', 'TextArea'), ('NUMBER', 'Number'), ('DATE', 'Date'), ('EMAIL', 'Email'), ('PHONE', 'Phone'), ('SELECT', 'Select'), ('CHECKBOX', 'Checkbox'), ('RADIO', 'Radio'), ('MULTISELECT', 'MultiSelect'), ('FILE', 'File Upload')], default='TEXT', max_length=20)),
                ('required', models.BooleanField(default=True)),
                ('placeholder', models.CharField(blank=True, max_length=255, null=True)),
                ('options', models.TextField(blank=True, help_text='Comma-separated values for Select, Radio, Checkbox, MultiSelect', null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='forms_engine.formdefinition')),
            ],
            options={
                'db_table': 'forms_field',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FormResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_role', models.CharField(max_length=50)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_responses', to='center.center')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='forms_engine.formdefinition')),
                ('subcenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_responses', to='subcenter.subcenter')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_form_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'forms_response',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, null=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='forms_engine.formfield')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='forms_engine.formresponse')),
            ],
            options={
                'db_table': 'forms_answer',
            },
        ),
        migrations.AddIndex(
            model_name='formresponse',
            index=models.Index(fields=['form', 'center', 'subcenter', 'submitted_at'], name='forms_respo_form_id_d425d9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('response', 'field')},
        ),
    ]
