# Generated by Django 5.2.15 on 2026-06-23 06:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('center', '0001_initial'),
        ('subcenter', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_role', models.CharField(max_length=50)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('house_number', models.CharField(max_length=50)),
                ('ward', models.CharField(db_index=True, max_length=100)),
                ('panchayat', models.CharField(db_index=True, max_length=100)),
                ('address', models.TextField()),
                ('family_head_name', models.CharField(max_length=255)),
                ('family_members_count', models.PositiveIntegerField(default=1)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_surveys', to='center.center')),
                ('subcenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_surveys', to='subcenter.subcenter')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_surveys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'surveys_health_survey',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='SurveyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField(db_index=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], db_index=True, max_length=1)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('diseases', models.TextField(blank=True, help_text='Comma-separated diseases (e.g. Fever, Hypertension, Tuberculosis)', null=True)),
                ('disabilities', models.TextField(blank=True, null=True)),
                ('vaccination_status', models.CharField(choices=[('FULLY', 'Fully Vaccinated'), ('PARTIALLY', 'Partially Vaccinated'), ('NOT', 'Not Vaccinated')], db_index=True, default='NOT', max_length=20)),
                ('is_pregnant', models.BooleanField(db_index=True, default=False)),
                ('blood_pressure_systolic', models.PositiveIntegerField(blank=True, null=True)),
                ('blood_pressure_diastolic', models.PositiveIntegerField(blank=True, null=True)),
                ('has_diabetes', models.BooleanField(db_index=True, default=False)),
                ('has_cancer', models.BooleanField(db_index=True, default=False)),
                ('mental_health_indicators', models.TextField(blank=True, null=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='surveys.healthsurvey')),
            ],
            options={
                'db_table': 'surveys_survey_member',
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='healthsurvey',
            index=models.Index(fields=['center', 'subcenter', 'submitted_at'], name='surveys_hea_center__0a0018_idx'),
        ),
        migrations.AddIndex(
            model_name='healthsurvey',
            index=models.Index(fields=['ward', 'panchayat'], name='surveys_hea_ward_9eed04_idx'),
        ),
        migrations.AddIndex(
            model_name='surveymember',
            index=models.Index(fields=['age', 'gender'], name='surveys_sur_age_843c2a_idx'),
        ),
        migrations.AddIndex(
            model_name='surveymember',
            index=models.Index(fields=['has_diabetes', 'has_cancer', 'is_pregnant'], name='surveys_sur_has_dia_3c5003_idx'),
        ),
    ]
